name: Nightly
on:
  schedule:
    - cron: '30 5 * * *'
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name to trigger the release'
        required: false
        default: 'nightly'

jobs:
  trigger:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          gh release create ${{ github.event.inputs.tag_name }} --title ${{ github.event.inputs.tag_name }} --generate-notes --prerelease

      - if: ${{ github.event_name == 'schedule' }}
        run: |
          if [[ $(git diff nightly --name-only -B -M -C) ]]; then
            gh release delete nightly --yes || true
            gh release create nightly --title nightly --generate-notes --prerelease
          fi
